apiVersion: v1
kind: ConfigMap
metadata:
  name: theme-studio-config
  namespace: theme-studio
data:
  NODE_ENV: "production"
  PORT: "3001"
  SCREENSHOT_BASE_URL: "http://theme-studio-svc:3001"
  EKP_TOKEN_RESOLVE_PATH: "/sys/authentication/sso/loginService_rest/getTokenLoginName"
  PUBLIC_BASE_URL: "https://cloud-theme.landray.com.cn"
---
apiVersion: v1
kind: Secret
metadata:
  name: theme-studio-secrets
  namespace: theme-studio
type: Opaque
stringData:
  ADMIN_PASSWORD: "123456"
  SECRET_ENCRYPTION_KEY: "9d3c0f7a9da90eb26103ba693a7524deff036e8c74bae753c42e8fb3f421a224"
  EKP_BASE_URL: "https://myekp.landray.com.cn"
  EKP_SSO_USER: "third_ai_01"
  EKP_SSO_PASS: "Y$F2JMj47!DTJu&"
